development:
 adapter: mysql
 encoding: utf8
 database: iff_development
 username: root
 host: 127.0.0.1
 password:

test:
  adapter: mysql
  encoding: utf8
  database: iff_test
  username: tang
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: iff_development
  username: tang 
  password: 
  host: localhost
